{"name": "test_exported_csv", "status": "failed", "statusDetails": {"message": "AssertionError: no data in csv !\nassert [] != []", "trace": "self = <testqawin.TestPlanQAWin object at 0x798f1218f110>, config = <configparser.ConfigParser object at 0x798f11f0d550>\ncsv_headers = ['БИК Плательщика', 'БИК Получателя', 'Сумма', 'Номер документа', 'Дата документа', 'Назначение платежа']\n\n    @allure.testcase(\"3.6 Check exported ED101.csv\")\n    def test_exported_csv(self, config, csv_headers):\n        assert os.path.exists(config[\"IMPORT\"][\"IMPRT_CSV_FILE\"]), \\\n            f\"a csv file {config[\"IMPORT\"][\"IMPRT_CSV_FILE\"]} has not been created !\"\n        headers, data = AdminTools.read_csv_headers(config[\"IMPORT\"][\"IMPRT_CSV_FILE\"])\n>       assert data != [], \"no data in csv !\"\nE       AssertionError: no data in csv !\nE       assert [] != []\n\ntestqawin.py:454: AssertionError"}, "start": 1748602693514, "stop": 1748602693516, "uuid": "66c1a4b3-cb81-4bb1-bce8-eba13562a5d1", "historyId": "08f12a43c23e786ea571e577982431ef", "testCaseId": "08f12a43c23e786ea571e577982431ef", "fullName": "testqawin.TestPlanQAWin#test_exported_csv", "labels": [{"name": "suite", "value": "Test QA"}, {"name": "subSuite", "value": "TestPlanQAWin"}, {"name": "host", "value": "Ubuntu-VM-Yand"}, {"name": "thread", "value": "14211-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testqawin"}], "links": [{"type": "tms", "url": "3.6 Check exported ED101.csv", "name": "3.6 Check exported ED101.csv"}]}